[package]
name = "amnz"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
ndarray = "0.17.2"
rayon = "1.11.0"
smartcore = { version = "0.4.9", features = ["ndarray-bindings"] }
